#!/usr/bin/env node
// Generates static blog cards into blog/index.html from blog/posts.json.
// Run after editing posts.json:  npm run build-blog
// Cards live between the BLOG-CARDS markers; everything else is untouched.
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const posts = JSON.parse(fs.readFileSync(path.join(root, 'blog', 'posts.json'), 'utf8'));
const indexPath = path.join(root, 'blog', 'index.html');
let html = fs.readFileSync(indexPath, 'utf8');

const MONTHS = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
const fmtDate = (d) => { const p = d.split('-'); return `${MONTHS[+p[1] - 1]} ${+p[2]}, ${p[0]}`; };
const slugCat = (c) => c.toLowerCase().replace(/\s+/g, '-');
const esc = (t) => t.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/"/g, '&quot;');

posts.sort((a, b) => new Date(b.date) - new Date(a.date));

const cards = posts.map((p, i) => `      <article class="blog-card reveal" data-category="${slugCat(p.category)}">
        <a href="${p.slug}" style="display:block">
          <img src="${p.image}" alt="${esc(p.title)}" class="blog-card-image" loading="${i < 2 ? 'eager' : 'lazy'}" width="600" height="315">
          <div class="blog-card-content">
            <span class="blog-cat">${p.category}</span>
            <h2>${esc(p.title)}</h2>
            <p class="blog-card-excerpt">${esc(p.excerpt)}</p>
            <div class="blog-card-meta">
              <span class="read-time">${p.readTime}</span>
              <span>${fmtDate(p.date)}</span>
            </div>
          </div>
        </a>
      </article>`).join('\n');

const START = '<!-- BLOG-CARDS:START — generated by scripts/build-blog.js, edit posts.json instead -->';
const END = '<!-- BLOG-CARDS:END -->';
const re = new RegExp(`${START.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}[\\s\\S]*?${END.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}`);
if (!re.test(html)) {
  console.error('Markers not found in blog/index.html');
  process.exit(1);
}
html = html.replace(re, `${START}\n${cards}\n      ${END}`);
fs.writeFileSync(indexPath, html);
console.log(`Wrote ${posts.length} static cards into blog/index.html`);
